[package]
name = "sudoku"
version = "1.0.0"
authors = ["William Bland"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
nannou = "*"
